Update HOST with Apple production API
harry1064/APNS2 pull request #7
Opened 2017-12-21 03:12 UTC by iranfard

When the certificate is only for production it does not work properly with this HOST so it's better to change to "api.push.apple.com" for production, or it's better to add boolean for production or development certificates

2017-12-21 07:05 UTC, harry1064 requested changes
@iranfard  Thanks. I have left a comment. Will you please address that comment before i can merge you request.

2017-12-21 07:05 UTC, harry1064 commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
@iranfard First of all thanks for pointing out this issue. I missed upon this because if you see line number 38, wou will see `options.host` which i was using to specify production host. But i forgot to mention that in my README.md file to specify while initializing APNS2 class instance. 

But now i think asking user to specify host is not good idea. Based on your suggestion, i am thinking to add a boolean key to specify production or not and internally change host based on this key.  Let me know if you are going to implement it.

2017-12-22 01:45 UTC, iranfard commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
Hi, thank you for your reply, I think a boolean for production is much more suitable for both development and production certificates. I can write it but it's my first time on Github so please check it after I pushed.

2017-12-22 02:47 UTC, iranfard commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
I've added production boolean for options and changed README.md, can you allow me to push?

2017-12-22 08:10 UTC, harry1064 commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
have you pushed it to github under your patch-1 branch because i am not able see it.

2017-12-23 01:30 UTC, iranfard commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
when I try to push with "git push origin patch-1" It says: 
remote: Permission to harry1064/APNS2.git denied to iranfard.
fatal: unable to access 'https://github.com/harry1064/APNS2.git/': The requested URL returned error: 403

2017-12-23 04:16 UTC, harry1064 commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
check your origin using the command `git remote -v`.  If you see https://github.com/harry1064/APNS2.git/ as your origin than there will be a problem.
Can you send me screenshot for the command `git remote -v`. After that i will explain you how to solve this issue.

2017-12-23 22:44 UTC, iranfard commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
Yes, it shows https://github.com/harry1064/APNS2.git

2017-12-26 07:23 UTC, harry1064 commented on lib/apns-http2.js
> +const HOST = 'api.push.apple.com';
Are you trying to push it from directly clone repository from my repository or are you working on forked repository of yours?

2017-12-27 04:13 UTC, iranfard commented
Thanks! You are right, I've just pushed it again to https://github.com/iranfard/APNS2.git and patch-1 branch.

2017-12-28 19:18 UTC, harry1064 approved these changes
This looks good. I going to merge this.

2017-12-28 19:19 UTC, merged

2017-12-29 01:48 UTC, iranfard commented
Thanks :)

2017-12-29 05:13 UTC, harry1064 commented
@iranfard you are welcome.